name: Build and Test

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
  push:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  swift_tests_latest:
    name: Latest Swift
    runs-on: macos-26
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: macos-latest-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            macos-latest-spm-

      - name: Create test configuration
        run: chmod +x ./build_configuration.sh && ./build_configuration.sh
        shell: bash

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
  swift_tests_previous:
    name: Swift 6.1
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.3"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: macos-14-swift-610-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            macos-14-swift-610-spm-

      - name: Create test configuration
        run: chmod +x ./build_configuration.sh && ./build_configuration.sh
        shell: bash

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
  swift_tests_previous_previous:
    name: Swift 6.0
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: macos-14-swift-600-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            macos-14-swift-600-spm-

      - name: Create test configuration
        run: chmod +x ./build_configuration.sh && ./build_configuration.sh
        shell: bash

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test